// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPgIVfXjpqeaun_v9PO1Xfd6mdVKwvog',
    appId: '1:248712468259:web:589a7b8a76e8fa879a9e96',
    messagingSenderId: '248712468259',
    projectId: 'tp2flutter-7b00a',
    authDomain: 'tp2flutter-7b00a.firebaseapp.com',
    storageBucket: 'tp2flutter-7b00a.appspot.com',
    measurementId: 'G-EPLLGQR2Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34P0CbBkLjnAnhYUstiqNh_ekhWOHUV8',
    appId: '1:248712468259:android:d3b62f744dda4cc09a9e96',
    messagingSenderId: '248712468259',
    projectId: 'tp2flutter-7b00a',
    storageBucket: 'tp2flutter-7b00a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCIkr_R3k_1KRS4oMBTmxxFgdP2rBk12A',
    appId: '1:248712468259:ios:86859883fdae97d09a9e96',
    messagingSenderId: '248712468259',
    projectId: 'tp2flutter-7b00a',
    storageBucket: 'tp2flutter-7b00a.appspot.com',
    iosClientId: '248712468259-7q3djkpfnm2p445j00694mmiopq9eqve.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCIkr_R3k_1KRS4oMBTmxxFgdP2rBk12A',
    appId: '1:248712468259:ios:86859883fdae97d09a9e96',
    messagingSenderId: '248712468259',
    projectId: 'tp2flutter-7b00a',
    storageBucket: 'tp2flutter-7b00a.appspot.com',
    iosClientId: '248712468259-7q3djkpfnm2p445j00694mmiopq9eqve.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2',
  );
}
